### ISSUE TITLE
Potential audio solution & trackpad fix

### ISSUE THREAD

**Issue by Drowningfish223** [robotblox/XPS-15-9500-Catalina-10.15.6#1]
Hey there @robotblox! 

Seems like you're a trailblazer and the only one to try hackintoshing an xps 9500 so far. You said that audio doesn't work with layout-id 30. The xps 9500 supposedly has an ALC 3281, and a google search reveals that ALC 3281 is just a renamed ALC 289. On [this list](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs), the makers of AppleALC recommend using layout 23 with audio codec ALC 289. You can implement that with the boot-arg alcid=23. I recommend trying that out, as using Apple ALC with a layout-id is the cleanest way to fix audio.

If AppleALC still doesn't work, try using VoodooHDA. I belive you can download the kext from sourceforge and use opencore to inject it. VoodooHDA is recommended against if AppleALC works, but it is a second option.

I may get an xps 9500 and I'm definitely interested in hackintoshing it if I do, so let me know how this fix goes! 

Also, you may be able to get a working trackpad by deleting VoodooI2C and its plugins. VoodooPS2 can enable a lower quality trackpad if you add VoodooInput.kext too. Your touchscreen will not work, though. I recommend re-reading the trackpad section of the dortania guide to make sure you have the right kexts minus VoodooI2C.

Good luck!

**Comment by robotblox** [comment]
Hi @Drowningfish223!

Zachs78 on Github has started working on hackintoshing a Dell XPS 9500 shortly after I started, and has made significant progress on it! I’d highly recommend checking his work out!

https://github.com/zachs78/MacOS-XPS-9500-OpenCore


As for the audio, layout 23 works for just audio but no mic. Layout 11, as discovered by zachs78, works for both the audio and mic

And as for the trackpad issues, it turns out that the touchscreen was causing the issues with VoodooI2C. After disabling it in BIOS the trackpad works wonderfully!

**Comment by Drowningfish223** [comment]
@robotblox Thanks for letting me know! Just a quick question-have you had any palm rejection issues with the large trackpad? I've had issues with smaller trackpads on other laptops, but the situation might be different because of the godly size of the 9500 trackpad. Thanks for getting back to me so quickly!
